In [166]:
# import libraries
import struct
import numpy as np
from scipy.signal import convolve2d


In [167]:
# Set params
N=1
M=1
K=3
R=4
C=4

In [168]:
# Generate input maps and weights
input_fm = np.random.uniform( 0, 1, ( N, R, C ) )
weights = np.random.uniform( 0, 1, ( M, N, K, K ) )

In [169]:
output_fm = np.zeros( ( M, R, C ) )
# compute convolution
for i in range( M ):
    # convolve each input fm and sum it together
    for j in range( N ):
        # mirror kernel
        kernel = np.flip(np.flip(weights[i][j],0),1)
        output_fm[i] += convolve2d( input_fm[j], kernel, mode='same')

# print(output_fm[0])


In [170]:
# write files
# write input_fm
with open('input_fm.dat', 'w') as f:
    for i in range(N):
        for row in range(R):
            for col in range(C):
                num = struct.unpack('!I', struct.pack('!f', input_fm[i][row][col]))[0]
                f.write(f"{num:032b}\n")

# write weights_fm
with open('weights.dat', 'w') as f:
    for i in range(M):
        for j in range(N):
            for row in range(K):
                for col in range(K):
                    num = struct.unpack('!I', struct.pack('!f', weights[i][j][row][col]))[0]
                    f.write(f"{num:032b}\n")

# write output_fm
with open('output_fm.dat', 'w') as f:
    for i in range(M):
        for row in range(R):
            for col in range(C):
                num = struct.unpack('!I', struct.pack('!f', output_fm[i][row][col]))[0]
                f.write(f"{num:032b}\n")
                

In [171]:
# write files in decimal
# write input_fm
with open('input_fm.test', 'w') as f:
    for i in range(N):
        for row in range(R):
            for col in range(C):
                f.write(f"{input_fm[i][row][col]:.7f}\n")

# write weights_fm
with open('weights.test', 'w') as f:
    for i in range(M):
        for j in range(N):
            for row in range(K):
                for col in range(K):
                    f.write(f"{weights[i][j][row][col]:.7f}\n")

# write output_fm
with open('output_fm.test', 'w') as f:
    for i in range(M):
        for row in range(R):
            for col in range(C):
                f.write(f"{output_fm[i][row][col]:.7f}\n")

In [172]:
print(input_fm)
print(weights)
print(output_fm)

[[[0.77876823 0.83834584 0.44207752 0.17073085]
  [0.50554184 0.76701984 0.09626479 0.83229128]
  [0.3767005  0.9311596  0.72429977 0.7828158 ]
  [0.01854674 0.90226254 0.99118977 0.12440259]]]
[[[[0.7450844  0.89299104 0.74411826]
   [0.31123649 0.55553515 0.78387263]
   [0.46333789 0.71202945 0.41897901]]]


 [[[0.77164164 0.54078499 0.29027136]
   [0.3950877  0.84628967 0.43791429]
   [0.76663622 0.03661701 0.53839729]]]]
[[[1.77111538 1.87535448 1.41298995 0.86965667]
  [2.8597118  3.4577693  3.36621469 1.8671578 ]
  [2.35261359 3.40185779 3.75852476 2.02309835]
  [1.74684531 2.93513305 2.8520668  1.61631639]]

 [[1.45765997 1.67823861 1.81976474 0.42342324]
  [1.9433452  2.78647692 2.84635825 1.75978547]
  [1.70905401 2.66778522 3.00415624 2.23746065]
  [0.88481252 2.20943764 2.58722515 1.47912242]]]
