In [127]:
# import libraries
import struct
import numpy as np
from scipy.signal import convolve2d


In [128]:
# Set params
N=1
M=1
K=3
R=4
C=4

In [129]:
# Generate input maps and weights
input_fm = np.random.uniform( 0, 1, ( N, R, C ) )
weights = np.random.uniform( 0, 1, ( N, M, K, K ) )

In [130]:
output_fm = np.zeros( ( M, R, C ) )
# compute convolution
for i in range( M ):
    # convolve each input fm and sum it together
    for j in range( N ):
        # mirror kernel
        kernel = np.flip(np.flip(weights[j][i],0),1)
        output_fm[i] += convolve2d( input_fm[j], kernel, mode='same')

# print(output_fm[0])


In [131]:
# write files
# write input_fm
with open('input_fm.dat', 'w') as f:
    for i in range(N):
        for row in range(R):
            for col in range(C):
                num = struct.unpack('!I', struct.pack('!f', input_fm[i][row][col]))[0]
                f.write(f"{num:032b}\n")

# write weights_fm
with open('weights.dat', 'w') as f:
    for i in range(N):
        for j in range(M):
            for row in range(K):
                for col in range(K):
                    num = struct.unpack('!I', struct.pack('!f', weights[i][j][row][col]))[0]
                    f.write(f"{num:032b}\n")

# write output_fm
with open('output_fm.dat', 'w') as f:
    for i in range(M):
        for row in range(R):
            for col in range(C):
                num = struct.unpack('!I', struct.pack('!f', output_fm[i][row][col]))[0]
                f.write(f"{num:032b}\n")
                

In [132]:
# write files in decimal
# write input_fm
with open('input_fm.test', 'w') as f:
    for i in range(N):
        for row in range(R):
            for col in range(C):
                f.write(f"{input_fm[i][row][col]:.7f}\n")

# write weights_fm
with open('weights.test', 'w') as f:
    for i in range(N):
        for j in range(M):
            for row in range(K):
                for col in range(K):
                    f.write(f"{weights[i][j][row][col]:.7f}\n")

# write output_fm
with open('output_fm.test', 'w') as f:
    for i in range(M):
        for row in range(R):
            for col in range(C):
                f.write(f"{output_fm[i][row][col]:.7f}\n")

In [133]:
print(input_fm)
print(weights)
print(output_fm)

[[[0.99912727 0.68886453 0.83942442 0.75191518]
  [0.85751783 0.9040124  0.48574069 0.18639838]
  [0.02036793 0.16910326 0.01182998 0.03038433]
  [0.05409501 0.01922742 0.57959395 0.0813523 ]]]
[[[[0.15611597 0.97473806 0.62777208]
   [0.15506927 0.55971888 0.07264831]
   [0.7725946  0.08766397 0.14942652]]]]
[[[0.81953208 1.41583268 1.40015869 0.9426511 ]
  [1.97903523 2.06099325 1.95962289 1.05542543]
  [1.43466966 1.54873589 0.84448866 0.73128545]
  [0.15768653 0.23669462 0.39030665 0.16687524]]]
