In [15]:
# import libraries
import struct
import numpy as np
from scipy.signal import convolve2d


In [16]:
# Set params
N=1
M=1
K=1
R=4
C=4

In [17]:
# Generate input maps and weights
input_fm = np.random.uniform( 0, 1, ( N, R, C ) )
weights = np.random.uniform( 0, 1, ( M, N, K, K ) )

In [18]:
output_fm = np.zeros( ( M, R, C ) )
# compute convolution
for i in range( M ):
    # convolve each input fm and sum it together
    for j in range( N ):
        # mirror kernel
        kernel = np.flip(np.flip(weights[i][j],0),1)
        output_fm[i] += convolve2d( input_fm[j], kernel, mode='same')

# print(output_fm[0])


In [19]:
# write files
# write input_fm
with open('input_fm.dat', 'w') as f:
    for i in range(N):
        for row in range(R):
            for col in range(C):
                num = struct.unpack('!I', struct.pack('!f', input_fm[i][row][col]))[0]
                f.write(f"{num:032b}\n")

# write weights_fm
with open('weights.dat', 'w') as f:
    for i in range(M):
        for j in range(N):
            for row in range(K):
                for col in range(K):
                    num = struct.unpack('!I', struct.pack('!f', weights[i][j][row][col]))[0]
                    f.write(f"{num:032b}\n")

# write output_fm
with open('output_fm.dat', 'w') as f:
    for i in range(M):
        for row in range(R):
            for col in range(C):
                num = struct.unpack('!I', struct.pack('!f', output_fm[i][row][col]))[0]
                f.write(f"{num:032b}\n")
                

In [21]:
# write files in decimal
# write input_fm
with open('input_fm.test', 'w') as f:
    f.write(f"{input_fm}")

# write weights_fm
with open('weights.test', 'w') as f:
    f.write(f"{weights}")

# write output_fm
with open('output_fm.test', 'w') as f:
    f.write(f"{output_fm}")


In [ ]:
print(input_fm)
print(weights)
print(output_fm)

[[[0.30483928 0.59963377 0.37179611 0.41385765]
  [0.98196631 0.48800693 0.08641591 0.85828344]
  [0.96327074 0.35065049 0.83423927 0.76872088]
  [0.93989854 0.0546957  0.58528876 0.62962907]]]
[[[[0.71473096]]]]
[[[0.21787807 0.42857682 0.26573419 0.29579688]
  [0.70184173 0.34879366 0.06176412 0.61344175]
  [0.68847942 0.25062077 0.59625664 0.54942861]
  [0.67177459 0.03909271 0.418324   0.45001539]]]
