In [22]:
# import libraries
import struct
import numpy as np
from scipy.signal import convolve2d


In [23]:
# Set params
N=1
M=1
K=1
R=4
C=4

In [24]:
# Generate input maps and weights
input_fm = np.random.uniform( 0, 1, ( N, R, C ) )
weights = np.random.uniform( 0, 1, ( M, N, K, K ) )

In [25]:
output_fm = np.zeros( ( M, R, C ) )
# compute convolution
for i in range( M ):
    # convolve each input fm and sum it together
    for j in range( N ):
        # mirror kernel
        kernel = np.flip(np.flip(weights[i][j],0),1)
        output_fm[i] += convolve2d( input_fm[j], kernel, mode='same')

# print(output_fm[0])


In [26]:
# write files
# write input_fm
with open('input_fm.dat', 'w') as f:
    for i in range(N):
        for row in range(R):
            for col in range(C):
                num = struct.unpack('!I', struct.pack('!f', input_fm[i][row][col]))[0]
                f.write(f"{num:032b}\n")

# write weights_fm
with open('weights.dat', 'w') as f:
    for i in range(M):
        for j in range(N):
            for row in range(K):
                for col in range(K):
                    num = struct.unpack('!I', struct.pack('!f', weights[i][j][row][col]))[0]
                    f.write(f"{num:032b}\n")

# write output_fm
with open('output_fm.dat', 'w') as f:
    for i in range(M):
        for row in range(R):
            for col in range(C):
                num = struct.unpack('!I', struct.pack('!f', output_fm[i][row][col]))[0]
                f.write(f"{num:032b}\n")
                

In [27]:
# write files in decimal
# write input_fm
with open('input_fm.test', 'w') as f:
    f.write(f"{input_fm}")

# write weights_fm
with open('weights.test', 'w') as f:
    f.write(f"{weights}")

# write output_fm
with open('output_fm.test', 'w') as f:
    f.write(f"{output_fm}")


In [28]:
print(input_fm)
print(weights)
print(output_fm)

[[[0.06407955 0.46965055 0.76658903 0.7961119 ]
  [0.74084279 0.86366429 0.82393051 0.90871405]
  [0.91384569 0.50779311 0.27031848 0.08583059]
  [0.10810058 0.11285779 0.76011271 0.17500887]]]
[[[[0.63413131]]]]
[[[0.04063485 0.29782012 0.48611811 0.50483948]
  [0.46979161 0.54767656 0.52248013 0.57624403]
  [0.57949816 0.32200751 0.17141741 0.05442786]
  [0.06854996 0.07156666 0.48201127 0.11097861]]]
