In [78]:
# import libraries
import numpy as np
from scipy.signal import convolve2d


In [79]:
# Set params
N=4
M=4
K=2
R=4
C=4

In [82]:
# Generate input maps and weights
input_fm = np.random.uniform( 0, 1, ( N, R, C ) )
weights = np.random.uniform( 0, 1, ( N, M, K, K ) )

In [86]:
output_fm = np.zeros( ( M, R, C ) )
# compute convolution
for i in range( M ):
    # convolve each input fm and sum it together
    for j in range( N ):
        output_fm[i] += convolve2d( input_fm[j], weights[i][j], mode='same')

print(output_fm[0])


[[0.91198184 2.24555756 2.39509612 2.15607616]
 [1.05117503 2.76403967 2.70568681 3.22687245]
 [1.43719822 3.75327938 3.35967878 2.88762182]
 [0.97795958 3.41655019 3.61216601 2.2014063 ]]
