In [20]:
# import libraries
import struct
import numpy as np
from scipy.signal import convolve2d


In [ ]:
# Set params
N=2
M=2
K=1
R=4
C=4

In [22]:
# Generate input maps and weights
input_fm = np.random.uniform( 0, 1, ( N, R, C ) )
weights = np.random.uniform( 0, 1, ( M, N, K, K ) )

In [23]:
output_fm = np.zeros( ( M, R, C ) )
# compute convolution
for i in range( M ):
    # convolve each input fm and sum it together
    for j in range( N ):
        # mirror kernel
        kernel = np.flip(np.flip(weights[i][j],0),1)
        output_fm[i] += convolve2d( input_fm[j], kernel, mode='same')

# print(output_fm[0])


In [24]:
# write files
# write input_fm
with open('input_fm.dat', 'w') as f:
    for i in range(N):
        for row in range(R):
            for col in range(C):
                num = struct.unpack('!I', struct.pack('!f', input_fm[i][row][col]))[0]
                f.write(f"{num:032b}\n")

# write weights_fm
with open('weights.dat', 'w') as f:
    for i in range(M):
        for j in range(N):
            for row in range(K):
                for col in range(K):
                    num = struct.unpack('!I', struct.pack('!f', weights[i][j][row][col]))[0]
                    f.write(f"{num:032b}\n")

# write output_fm
with open('output_fm.dat', 'w') as f:
    for i in range(M):
        for row in range(R):
            for col in range(C):
                num = struct.unpack('!I', struct.pack('!f', output_fm[i][row][col]))[0]
                f.write(f"{num:032b}\n")
                

In [25]:
# write files in decimal
# write input_fm
with open('input_fm.test', 'w') as f:
    f.write(f"{input_fm}")

# write weights_fm
with open('weights.test', 'w') as f:
    f.write(f"{weights}")

# write output_fm
with open('output_fm.test', 'w') as f:
    f.write(f"{output_fm}")


In [26]:
print(input_fm)
print(weights)
print(output_fm)

[[[0.29554891 0.42989325 0.6160341  0.69364711]
  [0.11537931 0.12994664 0.06128317 0.78274782]
  [0.69280258 0.47217271 0.99091064 0.33576005]
  [0.79326754 0.60074264 0.47877254 0.65249271]]]
[[[[0.94243552]]]


 [[[0.24461707]]]]
[[[0.27853579 0.40514667 0.58057241 0.65371767]
  [0.10873756 0.12246633 0.05775543 0.73768935]
  [0.65292176 0.44499234 0.93386939 0.3164322 ]
  [0.7476035  0.5661612  0.45121224 0.6149323 ]]

 [[0.07229631 0.10515923 0.15069246 0.16967793]
  [0.02822375 0.03178717 0.01499091 0.19147348]
  [0.16947134 0.11550151 0.24239366 0.08213264]
  [0.19404678 0.14695191 0.11711594 0.15961086]]]
